FROM node:22

# Install system dependencies (fixed for Debian-based image)
RUN apt-get update && apt-get install -y \
    git \
    python3 \
    make \
    g++ \
    redis-server \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json yarn.lock /app/
RUN yarn install --ignore-optional --frozen-lockfile

COPY . /app
RUN yarn build



EXPOSE 5174
CMD ["/app/start.sh"]